name: Bug report
description: Create a report to help us improve CrewAI
title: "[BUG]"
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step process to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots-code
    attributes:
      label: Screenshots/Code snippets
      description: If applicable, add screenshots or code snippets to help explain your problem.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g., Ubuntu 20.04, macOS Catalina, Windows 10
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: e.g., 3.8, 3.9, 3.10
    validations:
      required: true

  - type: input
    id: crewai-version
    attributes:
      label: crewAI Version
      description: e.g., 0.30.11
    validations:
      required: true

  - type: input
    id: crewai-tools-version
    attributes:
      label: crewAI Tools Version
      description: e.g., 0.2.6
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Include relevant logs or error messages if applicable.
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: Have a solution in mind? Please suggest it here, or write "None".
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: true
